### PR TITLE
Ligand task fix

### PR DESCRIPTION
**Pull request by cgoliver**
Add the `neglog_aff` field to the protein ligand dataset, and updated the target attribute.

### CODE REVIEW

**Comment by cgoliver** [comment]
@timkucera i'm suspecting this fails because there is no previous build of the dataset on the server? I was able to run with `use_precomputed=False` locally with no error.

**Comment by timkucera** [comment]
is this `INDEX_refined_data.2020` file new?

**Comment by cgoliver** [comment]
It comes with the pdbbind download, but it is new in the sense that we were previously looking up affinities in a different file.

**Comment by timkucera** [comment]
is it a meta file like the tm-scores which we need to host as well?

**Comment by timkucera** [comment]
if yes, we need to extend the `download_precomputed` method in the PLI dataset to also download the meta file and save it as an attribute of the dataset. I can do it later

**Pull request merged**
